# Generated by Django 5.2 on 2025-05-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_options_remove_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(choices=[('inStock', 'В наличии'), ('outOfStock', 'Нет в наличии')], default=True, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='Бестселлер'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_hot_sales',
            field=models.BooleanField(default=False, verbose_name='Горячая продажа'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
    ]
