# Generated by Django 5.2 on 2025-05-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_availability_product_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(choices=[('inStock', 'В наличии'), ('outOfStock', 'Нет в наличии')], default=True),
        ),
    ]
